
sudo: true

branches:
        only:
                - dev

before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq

install:
        - sudo apt-get install -qq gcc-4.9 g++-4.9 libsfml-dev lua5.2 liblua5.2-dev libluabind-dev
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
        - sudo ln -s /usr/include/lua5.2/lua.h /usr/include/lua.h
        - sudo ln -s /usr/include/lua5.2/lauxlib.h /usr/include/lauxlib.h

script:
        - scons

compiler:
        - gcc

