
sudo: true

branches:
        only:
                - dev

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install gcc-4.9 libsfml-dev liblua5.2-dev libluabind-dev

script:
        - scons

compiler:
        - gcc

